Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
num, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

num <- 1
para soma <- 0 ate 99 faca
escreval (soma, "+", num, " = ", num+soma )
fimpara
Fimalgoritmo